import {NextPage} from "next";
import {ReactElement, useState} from "react";
import {businessName, cc} from "../common/variables";
import Head from "next/head";
import Image from "next/image";
import useScreenOrientation, {orientations} from "../hooks/useOrientation";
import {darkTheme, lightTheme} from "../features/theme/themeSlice";
import Link from "next/link";
import {AppDispatch, RootState} from "../app/store";
import {useDispatch, useSelector} from "react-redux";
import Navbar from "../components/Navbar";
import {navbarOpenOrClosedOptions} from "../features/navbar/navbarOpenOrClosedSlice";

function Gallery<NextPage>(): ReactElement{
    const dispatch: AppDispatch = useDispatch();
    const screenOrientation = useScreenOrientation();
    const navbarState: string = useSelector((state: RootState) => state.navbarOpenOrClosed.value);

    return (
        <div className={'container' + (navbarState === navbarOpenOrClosedOptions.open ? " active" : "") }>
            <Head>
                <title>{businessName}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar/>

            <div className={"main-container"}>
                <div className={"main"}>
                    <header>`
                        <Image src={(screenOrientation === orientations.landscape ? '/backgrounds/hp.jpg' : '/backgrounds/mw.jpg')} layout={'fill'} objectFit={'cover'}
                               objectPosition={'center'}/>
                        <div className={"overlay"}>
                            <div className={"inner"}>
                                <h2 className={"title"}>Future is here</h2>
                                <p>
                                    <button onClick={() => { dispatch(lightTheme()); }}>Light </button>
                                    <button onClick={() => { dispatch(darkTheme()); }}>Dark </button>

                                </p>
                                <button className={"btn"}>Read more</button>
                            </div>
                        </div>
                    </header>
                </div>

                <div className={"shadow one"}></div>
                <div className={"shadow two"}></div>
            </div>

            <div className={"links"}>
                <ul>
                    <li>
                        <Link href={"/"}>
                            <a style={{"--i": "0.05s"}}>Home</a>
                        </Link>
                    </li>
                    <li>
                        <Link href={"/gallery"}>
                            <a style={{"--i": "0.15s"}}>Gallery</a>
                        </Link>
                    </li>
                    <li>
                        <a href="#" style={{"--i": "0.15s"}}>Portfolio</a>
                    </li>
                    <li>
                        <a href="#" style={{"--i": "0.2s"}}>Testimonials</a>
                    </li>
                    <li>
                        <a href="#" style={{"--i": "0.25s"}}>About</a>
                    </li>
                    <li>
                        <a href="#" style={{"--i": "0.3s"}}>Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    );
}

export default Gallery;