import type { NextPage } from 'next'
import type {AppDispatch} from "../app/store";
import type {ReactElement} from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {darkTheme, lightTheme} from "../features/theme/themeSlice";
import {useDispatch} from "react-redux";
import Link from "next/link";

function Home<NextPage>(): ReactElement{
  const dispatch: AppDispatch = useDispatch();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={() => { dispatch(lightTheme()); }}>Light</button>
        <button onClick={() => { dispatch(darkTheme()); }}>Dark</button>
        <Link href={"/test"}>Test page</Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
