import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from "next/script";
import Document from "next/document";
import {darkTheme, lightTheme} from "../features/theme/themeSlice";
import {useDispatch} from "react-redux";
import Link from "next/link";
import dynamic from "next/dynamic";
import {useEffect} from "react";
import useSWR from "swr";
import {serverUrl} from "../common/variables";
import httpClient from "../common/httpClient";

let cc = console.log;



function Test<NextPage>(){
    const {leafletData, leafletError, leafletIsLoading} = useSWR(`${serverUrl}/leaflet/getImagePaths`, leafletFetcher);
    const MapWithNoSSR = dynamic(() => import("../components/LeafletMap"), {
        ssr: false
    });

    //cc(MapWithNoSSR)

    return (
        <div className={styles.container}>

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

            </Head>

            <main className={styles.main}>
                <button onClick={(e) => {
                    leafletFetcher(leafletData, leafletError, leafletIsLoading);
                }}>Log</button>
                <div id={"map"} className={"height: 100px;"}>
                    <MapWithNoSSR />
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
                </a>
            </footer>
        </div>
    )
}

async function leafletFetcher(leafletData, leafletError, leafletIsLoading){
    //cc(this);
    let x = await httpClient.get(`${serverUrl}/leaflet/getImagePaths`);
    cc(x);

}

export default Test;
