import Image from "next/image";
import {GalleryInputs, GalleryInputsWithDefaults, ImageArrayFormat} from "../types/njGallery";
import {ReactElement} from "react";
import {cc} from "../../common/variables";
const layoutGeometry = require('../justified-layout');

export function createGalleryLayout(galleryInputWithDefaults: GalleryInputsWithDefaults, galleryElementRef: ReactElement): ReactElement[]{
    const galleryInputCopy: GalleryInputsWithDefaults = {...galleryInputWithDefaults}
    const {images, imagePadding} = galleryInputCopy;
    const imageLayout: ImageArrayFormat = calculateGalleryLayout(galleryInputCopy, galleryElementRef);
    const reformattedImageData = reformatGalleryData(imageLayout, images);

    return reformattedImageData.map((e, k) => {
        e.height = Math.trunc(+e.boxHeight);
        e.width = Math.trunc(+e.boxWidth);

        return (
                <div
                    style={{ "margin": (imagePadding.vertical/2) + "px " + (imagePadding.horizontal/2) + "px " + (imagePadding.vertical/2) + "px " + (imagePadding.horizontal/2) + "px", }}
            key={k}
            >
            <Image
                src={e.imgSrc}
            blurDataURL={e.imgBlurSrc}
            placeholder={e.imgBlurSrc && "blur"}
            className={"njGalleryImage"}
            width={e.boxWidth}
            height={e.boxHeight}
            alt={e.alt}
            />
            </div>
        );
    });
}

export function calculateGalleryLayout(galleryInputCopy: GalleryInputs, galleryElementRef): ImageArrayFormat{
    const { images, containerPadding, targetRowHeight, imagePadding, maxRows, showIncompleteRows, targetRowHeightTolerance } = galleryInputCopy;

    const imageDimensions = images.map((e) => {
        return {width: e.width, height: e.height}
    });

    const elementMinimumPadding = containerPadding;
    let galleryElementWidth;
    galleryElementRef?.current?.offsetWidth ? galleryElementWidth = galleryElementRef?.current?.offsetWidth-4 : galleryElementWidth = 14; // -4 because otherwise at some widths, the last image in a row jumps to the next row. Total width might be e.g. 0.42 pixels too large.
    if ((galleryElementWidth - elementMinimumPadding) < 14) galleryElementWidth = 14 + elementMinimumPadding;

    const autoGeneratedWidth = Math.trunc(galleryElementWidth);
    const imageLayout = layoutGeometry(imageDimensions, {
            containerWidth: autoGeneratedWidth,
            targetRowHeight: targetRowHeight || 300,
            containerPadding: containerPadding,
            boxSpacing: imagePadding,
            maxNumRows: maxRows,
            showWidows: showIncompleteRows,
            targetRowHeightTolerance: targetRowHeightTolerance,
            edgeCaseMinRowHeight: 80,
        }
    );

    return imageLayout;
}

export function reformatGalleryData(imageLayout, images){
    const imagesCopy = [...images];
    let reformattedGalleryData = [];

    for (let i = 0; i < imageLayout.boxes.length; i++){
        reformattedGalleryData[i] = {};
        reformattedGalleryData[i].boxHeight = imageLayout.boxes[i].height;
        reformattedGalleryData[i].boxWidth = imageLayout.boxes[i].width;
        reformattedGalleryData[i].imgSrc = imagesCopy[i].src;
        reformattedGalleryData[i].imgBlurSrc = imagesCopy[i].blurSrc;
        reformattedGalleryData[i].alt = imagesCopy[i].alt;
    }

    cc(reformattedGalleryData)

    return reformattedGalleryData;
}
